ARG BASE_IMAGE
FROM ${BASE_IMAGE}
LABEL continuum.image.owner="ext.luohaowen1" continuum.image.purpose="shared-django-dependencies"
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN conda create --yes --override-channels --channel conda-forge \
    --name testbed python=3.6 pip \
    && conda clean --all --yes
ENV PATH=/opt/miniconda3/envs/testbed/bin:/opt/miniconda3/bin:$PATH
COPY django-requirements.txt /opt/continuum-build/requirements.txt
RUN python -m pip install --no-cache-dir -r /opt/continuum-build/requirements.txt
COPY activate-testbed.sh /etc/profile.d/continuum-testbed.sh
COPY activate-testbed.sh /root/.bashrc
RUN python -m pip check \
    && python -m pip freeze > /opt/continuum-build/dependency-pip-freeze.txt \
    && /opt/miniconda3/bin/conda list -n testbed --explicit > /opt/continuum-build/conda-explicit.txt \
    && dpkg-query -W > /opt/continuum-build/dpkg-versions.txt
WORKDIR /testbed
CMD ["/bin/bash"]
